services:
  postgres:
    image: postgres:17
    container_name: solicita-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: solicita
      POSTGRES_USER: solicita
      POSTGRES_PASSWORD: solicita

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
