spring.application.name=solicita

spring.datasource.url=jdbc:postgresql://localhost:5432/solicita
spring.datasource.username=solicita
spring.datasource.password=solicita
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true